### ISSUE TITLE
GUI Reorganization

### ISSUE THREAD

**Issue by marty-pmr** [slaclab/pabv_control#10]
Move display and logging controls to a second page.
Make RR, Tinspiration, Trigger Pressure bigger.
Introduce PIP max parameter
Show measured peak PIP as number.
Show measured PEEP as number
Remove 3 state relay control from page and replace with:
         ON switch, large button outlined in green and filled with green when operating. On= cycling
         OFF switch Off = relay off. Off is large button outlined in red. First push causes green on light and red off light to to flash, and instruction to press off again to turn off ventilation. 2nd push turns off vent, green is off, red is steady.

**Comment by mwittgen** [comment]
@slacrherbst Is this mostly done and can be closes?

**Comment by bungernut** [comment]
We still need to figure out how to get PEEP per cycle. I see recent commit addresses PIPMax measurement 74dabacaf90a93a216b626a873a1eb936a20e299
