### ISSUE TITLE
Pressure, Flow and Volume Calcs

### ISSUE THREAD

**Issue by marty-pmr** [slaclab/pabv_control#11]
I think it would be a good move to send the calcs for Pressure, Flow, and Volume (PFV) to the Arduino. We will need it for Brian's display, and I really want to do an experiment related to the FDA papers: Set a Vmax parameter in the GUI and close the valve when V>Vmax. 
Then 3 numbers flow from the Arduino towards the GUI.  Is there any possibility of straing the Arduino doing this?

**Comment by mwittgen** [comment]
@slacrherbst I guess this can be closed as well?

**Comment by mwittgen** [comment]
Looks like this is done. Reopen otherwise.
