### ISSUE TITLE
GUI Parameter Names

### ISSUE THREAD

**Issue by bungernut** [slaclab/pabv_control#111]
PMax not PIPMax

**Comment by marty-pmr** [comment]
Also:
On pressure plot legend: P_thresh_hi ->PMax
P_thresh_low -> Vol Inh P


On inputs: V_Max ->VMax
On Volume plot legend: V_threshold_high ->VMax

On Expert Tab: Hide PiP Offset (not in use)

Format I:E

**Comment by bungernut** [comment]
@marty-pmr `P_thresh_low -> Vol Inh P`
Vol looks a lot like volume, is there any other ideas?

**Comment by bungernut** [comment]
new branch issue111 for this

**Comment by bungernut** [comment]
@marty-pmr how about `PSV Trg`?
