### ISSUE TITLE
Serious bug somewhere in communication between nanos and GUI

### ISSUE THREAD

**Issue by marty-pmr** [slaclab/pabv_control#129]
With the display connected and operating, PMax and VMAX cannot be changed on the GUI - they bounce back to the value on the display panel. Other parameters seem to work properly, including changing the display to match the GUI. 

Also when changing On/Off on the GUI, the display follows properly. But when changing On/Off on the Display, theGUI does not follow.

**Comment by slacrherbst** [comment]
This has been fixed in devel.
