### ISSUE TITLE
Move important data 1

### ISSUE THREAD

**Issue by marty-pmr** [slaclab/pabv_control#19]
In the Arduino, for each cycle, pick off measured PIP and PEEP and send to python.

**Comment by mwittgen** [comment]
@marty-pmr with more data sent the serial line might not keep up:
57600 bits / sec = 5760 bytes /sec (start,stop,8 data bits) 
limiting the message size to 57 bytes at 100Hz.
Is the 100Hz data rate a strict requirement? Or should certain channels be sent at different rates?

**Comment by marty-pmr** [comment]
The cycle status data should move once every 2-3 seconds. Should not be a problem.
