### ISSUE TITLE
NANO EEPROM is more complicated

### ISSUE THREAD

**Issue by bungernut** [slaclab/pabv_control#27]
Need to use a EEPROM emulator and flash memeory

https://github.com/cmaglie/FlashStorage

Limits writes to 10000 and these values will be reset every flash, but persist through resets.

**Comment by bungernut** [comment]
Starting to address this 737ba07ef7644da8180830051714293dee7cef32

**Comment by sluitz** [comment]
Add a serial EEPROM (e.g. Microchip 24LC256) to the shield?  >1E6 erase/write cycles. Still needs library but at least it's not messing with the flash and persistent through firmware upgrades.

**Comment by bungernut** [comment]
I see no harm in laying it out in the next board, if we use it TBD

**Comment by mwittgen** [comment]
We are using the internal nano flash memory.
