### ISSUE TITLE
scrolling display

### ISSUE THREAD

**Issue by bungernut** [slaclab/pabv_control#3]
>10Hz (25Hz preferable) for the waveforms.

**Comment by marty-pmr** [comment]
I hope the Python has a enough power for this - I don't see why not. The lack of a real scrolling display seems a little archaic.

**Comment by marty-pmr** [comment]
I think my laptop problem has little to do with GUI.

**Comment by mwittgen** [comment]
@bungernut The display is scrolling in the latest version. Can you confirm and close?

**Comment by bungernut** [comment]
master or devel or both?

**Comment by mwittgen** [comment]
They are in sync as of now.

**Comment by bungernut** [comment]
confirmed w/ MIB using Uno this morning
