### ISSUE TITLE
Ventilation hangs when python client starts

### ISSUE THREAD

**Issue by kernal42** [slaclab/pabv_control#37]
When a user starts up the python GUI, the arduino-controlled ventilation hangs for O(5) seconds.

**Comment by mwittgen** [comment]
Is this through a USB connection to the arduino? USB resets the board and there is a 5 seconds startup delay on the arduino.

**Comment by kernal42** [comment]
Yes, this is with USB connection.  That sounds like the explanation!

**Comment by mwittgen** [comment]
Closing this issue. The arduino uptime should be displayed in the GUI though.
