### ISSUE TITLE
Log reliability

### ISSUE THREAD

**Issue by bungernut** [slaclab/pabv_control#4]
Marty says the log is not bullet proof, not sure what that means.

**Comment by marty-pmr** [comment]
Opening a file should be confirmed, as should closing. Opening twice seems to make a mess. The file itself seems pretty good, but should be well defined as to what it is.

**Comment by mwittgen** [comment]
@marty-pmr @bungernut where do we stand on this?

**Comment by bungernut** [comment]
I think only Ryan knows, maybe Marty does... probably not addressed though
________________________________

**Comment by marty-pmr** [comment]
I think this is still open. Not sure whether we need logging - perhaps for debugging???

**Comment by mwittgen** [comment]
It should be removed then, the current version crashes. A true login feature might be better implemented on the arduino (not suggesting this). The client GUI as of now is stateless and adding file logging adds a dependency on the Win 10 laptop state. As of now the client could simply run from a USB stick and does not depend on any external  storage state and resources.

**Comment by marty-pmr** [comment]
I have been using the log files to calibrate the spirometer. There could be ways of doing it without the log files…m

**Comment by mwittgen** [comment]
Closing this for now. Has been fixed in devel.
