### ISSUE TITLE
Measure IT time in volume mode

### ISSUE THREAD

**Issue by bungernut** [slaclab/pabv_control#55]
If we go ahead with GUI modes for pressure control and volume control.

Volume control compresses the bag until a volume threshold is reached. This time depends on the patient lung compliance and the leak valve setting. It is necessary in our design to tune the input leak valve to achieve near the specified inhalation time (IT). For that reason it would be nice to know when the relay state closes and opens to display the time in the GUI.

**Comment by slacrherbst** [comment]
Pull request #80 adds a currState property to the AmbuControl class which provides access to the current state of the arduino cycle control state machine. 0 = paddle down, 1 = paddle up, 2 = paddle hold.
