### ISSUE TITLE
Flattop Valve

### ISSUE THREAD

**Issue by marty-pmr** [slaclab/pabv_control#57]
We want to add the option of a second valve controlling the exhaust timing to make volume control really work.
To keep things straight, the existing valve is called Main, and its control does not change at all.
The new valve, called Exhaust, is a separate pin on the Arduino. 
Exhaust turns ON at the end of tinspiration (usually 1 second)
Exhaust turns OFF at the beginning of a cycle. (Either by the timer or a voluntary breath)

**Comment by slacrherbst** [comment]
Addressed in #80
