### ISSUE TITLE
Watchdog

### ISSUE THREAD

**Issue by marty-pmr** [slaclab/pabv_control#71]
Can we implement the internal Nano watchdog?

**Comment by mwittgen** [comment]
@marty-pmr @bungernut @slacrherbst 
here's an implementation of a watchdog timer, triggering if not cleared after 64ms.
https://github.com/slaclab/pabv_control/tree/watchdog_timer
It used this library here:
https://github.com/javos65/WDTZero
I tested the code and the watchdog timer works, no guarantee on other side effects, like GUI behavior, or endless restart looping.

**Comment by mwittgen** [comment]
Implemented with the internal SAMD21 timer watchdog
