### ISSUE TITLE
GUI fix values changing under user

### ISSUE THREAD

**Issue by bungernut** [slaclab/pabv_control#79]
I would propose the following to fix the user's input being updated every status update (1Hz), making it impossible to change values. 

Add state variables to control_gui.py
```
--- a/python_client/control_gui.py
+++ b/python_client/control_gui.py
@@ -112,10 +112,15 @@ class ControlGui(QWidget):
         self.ambu = ambu
         self.ambu.setDataCallBack(self.dataUpdated)
         self.ambu.setStateCallBack(self.stateUpdated)
+        self.respRateVal  = 0.0
         self.respRate     = None
+        self.inhTimeVal   = 0.0
         self.inhTime      = None
+        self.volInhTholdVal = 0.0
         self.volInhThold  = None
+        self.pipMaxVal    = 0.0
         self.pipMax       = None
+        self.volMaxVal    = 0.0
```

Check if value changes from ambu before updating
```
@@ -775,11 +781,16 @@ class ControlGui(QWidget):
     def stateUpdated(self):
...
+        if self.ambu.volMax != self.volMaxVal:
+            self.updateVolMax.emit("{:0.1f}".format(self.ambu.volMax))
+            self.volMaxVal = self.ambu.volMax
```

Need to figure out a way to check if text() disagrees w/ stored value and make the box red or something, and then I would say a 10 second timeout should be applied to reset the text if it's not being changed anymore and it disagrees.

**Comment by slacrherbst** [comment]
The ambu_control.py file already does this. The problem is i got lazy and over used the callback. Issue_70 branch will address this.
