### ISSUE TITLE
Speeding up matplotlib plots

### ISSUE THREAD

**Issue by bungernut** [slaclab/pabv_control#81]
I'm getting 0.143s execute times for the `dataUpdated()` method which draws the plots. I'm hoping to shave a lot of cycles by finding a more efficient method

**Comment by bungernut** [comment]
Currently investigating this
https://bastibe.de/2013-05-30-speeding-up-matplotlib.html

**Comment by mwittgen** [comment]
pyqtgraph branch is available speeding up plotting.
