### ISSUE TITLE
Volume Correction

### ISSUE THREAD

**Issue by marty-pmr** [slaclab/pabv_control#83]
The existing calculation in the Python should be something like Varduino = Vmax+Voffset.
Let's try Varduino =Vmax - (-0.0011*Vmax^2 + 0.3005*Vmax + 87.95) +Voffset

**Comment by bungernut** [comment]
The arduino does not take input one parameter, it takes in Vmax and Voffset. TO do this, I would need to change the ardunio code.

Since the GUI reflects the values in the arduino, not something abstracted, there is no easy way to implement this in my opinion.

**Comment by marty-pmr** [comment]
Aha, you are right. Curses, foiled again.

**Comment by slacrherbst** [comment]
This is done right?
