### ISSUE TITLE
Changes For Alarm Display

### ISSUE THREAD

**Issue by marty-pmr** [slaclab/pabv_control#92]
1. Remove CLEAR from green banner.
2. for PIP MAX (Red) "Peak Patient Inspiratory pressure exceeded. Check PIP Valve"
3. Vol Low Alarm (Red) "Low Tidal Volume. Check Ventilator, patient circuit"
4. 12 V (Red) "Electrical power lost"
5. 9 V (Yellow) "Alarm battery low. Replace soon"
6. Pressure Low (Red) "Patient Inspiratory Pressure Low, Check patient circuit"
7. Peep Min (Yellow) "Pressure below PEEP. Check patient circuit"

**Comment by mwittgen** [comment]
@marty-pmr currently only one alarm condition is displayed on the banner. How do the alarm and warning condition rank?
alarms have a higher display priority than warnings, but we would need to sort alarm and warning conditions.

**Comment by marty-pmr** [comment]
Hi Matthias,

I would like to try scrolling through alarms and warnings, say 2 second shots…

Thanks,

Marty

**Comment by mwittgen** [comment]
Addressed in latest devel
